version: '3.8'

services:
  #backend:
  backendnode:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  frontendflask:
    # image: maeddes/frontendflask
    build:
      context: ./frontendflask # Assuming your frontend is in the 'frontend' directory
      dockerfile: Dockerfile
    environment:
      API_URL: "http://localhost:8080/api/shopping" # Use the API URL for communication between containers
    ports:
      - "5000:5000"
    depends_on:
      - backendnode
    restart: always
