version: '3.8'

services:
  #backend:
  backendnode:
    image: backend:v1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  frontendflask:
    image: maeddes/frontendflask:hse24
    #build:
    #  context: ./frontendflask # Assuming your frontend is in the 'frontend' directory
    #  dockerfile: Dockerfile
    environment:
      API_URL: "http://backendnode:8080/api/shopping" # Use the API URL for communication between containers
    ports:
      - "5000:5000"
    depends_on:
      - backendnode
    restart: always
