apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backendjs
  name: backendjs
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backendjs
  type: LoadBalancer
status:
  loadBalancer: {}